version: '3.7'

services:
  environment:
    container_name: environment
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3005:3005
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node app.js